
version: "3.9"

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8080:80"   # expose nginx on host
    volumes:
      - .:/app
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel

  redis:
    image: redis:alpine
    container_name: online_careers_redis
    ports:
        - "6380:6379"

  mysql:
    image: mysql:8.4
    container_name: mysql_data
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: laravel
        MYSQL_USER: laravel
        MYSQL_PASSWORD: laravel
    volumes:
        - mysql_data:/var/lib/mysql
    ports:
        - "3307:3306"

volumes:
  mysql_data:

